image: circleci/android:api-29

stages:
  - build
  - test
  - publish

build:
  tags:
    - sdk
  stage: build
  except:
    - branches
  script:
    - ./gradlew assembleDebug
  artifacts:
    expire_in: 2 hours
    paths:
      - app/build/outputs/
      - app-playfab/build/outputs/
      - app-simplified/build/outputs/
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

test:
  tags:
    - sdk
  stage: test
  except:
    - branches
  script:
    - ./gradlew test
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

generateDebugApp:
  tags:
    - sdk
  stage: publish
  except:
    - branches
  before_script:
    - mkdir -p artifacts
    - touch ./artifacts/info.txt
    - echo "Build date          $(date)"                >> ./artifacts/info.txt
    - echo "Git tag             ${CI_COMMIT_REF_NAME}"  >> ./artifacts/info.txt
    - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./artifacts/info.txt
    - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./artifacts/info.txt
  script:
    - mv app/build/outputs/apk/debug/app-debug.apk ./artifacts/SampleApp-Default.apk
    - mv app-playfab/build/outputs/apk/debug/app-playfab-debug.apk ./artifacts/SampleApp-Playfab.apk
    - mv app-simplified/build/outputs/apk/debug/app-simplified-debug.apk ./artifacts/SampleApp-Simplified.apk
    - mv app-inventory/build/outputs/apk/debug/app-inventory-debug.apk ./artifacts/SampleApp-Inventory.apk
  artifacts:
    expire_in: 2 hours
    paths:
      - artifacts

publishLogin:
  tags:
    - sdk
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-login-sdk:bintrayUpload
    - ./gradlew :xsolla-login-sdk-facebook:bintrayUpload
    - ./gradlew :xsolla-login-sdk-google:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

publishStore:
  tags:
    - sdk
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-store-sdk:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

publishInventory:
  tags:
    - sdk
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-inventory-sdk:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

publishPayments:
  tags:
    - sdk
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-payments-sdk:bintrayUpload
    - ./gradlew :xsolla-payments-sdk-playfab:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*